// * ------------- AUTHENTICATE JWT TOKEN MIDDLEWARE -------------
export const NO_JWT_TOKEN_AUTHENTICATE_JWT_TOKEN: number = 300;
export const INVALID_JWT_TOKEN_AUTHENTICATE_JWT_TOKEN: number = 301;
export const NO_USER_FOUND_IN_DATABASE_INSIDE_JWT_DECODED_TOKEN_AUTHENTICATE_JWT_TOKEN: number = 302;

// * ------------- VERIFY PRIVATE CSRF TOKEN MIDDLEWARE -------------
export const NO_CSRF_TOKEN_VERIFY_PRIVATE_CSRF_TOKEN: number = 303;
export const INVALID_CSRF_TOKEN_VERIFY_PRIVATE_CSRF_TOKEN: number = 304;

// * ------------- VERIFY PUBLIC CSRF TOKEN MIDDLEWARE -------------
export const NO_CSRF_TOKEN_VERIFY_PUBLIC_CSRF_TOKEN: number = 305;
export const INVALID_CSRF_TOKEN_VERIFY_PUBLIC_CSRF_TOKEN: number = 306;

// * ------------- LOGIN CONTROLLER -------------
export const INCOMPLETE_LOGIN_FORM: number = 307;
export const INVALID_USER_INPUT_LOGIN: number = 308;
export const USERNAME_NOT_EXIST_LOGIN: number = 309; 
export const PASSWORD_NOT_MATCH_LOGIN: number = 310; 
export const USER_SSO_ACCOUNT_LOGIN: number = 311;

// * ------------- VERIFICATION CODE LOGIN CONTROLLER -------------
export const INCOMPLETE_LOGIN_FORM_VERIFICATION_CODE_LOGIN: number = 312;
export const INVALID_OR_EXPIRED_MULTI_FACTOR_AUTHENTICATION_LOGIN_CODE: number = 313;
export const INVALID_USER_INPUT_VERIFICATION_CODE_LOGIN: number = 314;
export const USER_NOT_EXIST_VERIFICATION_CODE_LOGIN: number = 315;
export const VERIFICATION_CODE_LOGIN_NOT_MATCH: number = 316;
export const EXPIRED_VERIFICATION_CODE_LOGIN: number = 317;

// * -------------- GOOGLE AUTHENTICATOR CODE LOGIN CONTROLLER ----------------
export const INCOMPLETE_LOGIN_FORM_GOOGLE_AUTHENTICATOR_CODE_LOGIN: number = 318;
export const INVALID_OR_EXPIRED_MULTI_FACTOR_AUTHENTICATION_LOGIN_CODE_GOOGLE_AUTHENTICATOR_CODE_LOGIN: number = 319;
export const INVALID_USER_INPUT_GOOGLE_AUTHENTICATOR_CODE_LOGIN: number = 320;
export const INVALID_GOOGLE_AUTHENTICATOR_CODE_LOGIN: number = 321;

// * ------------- REGISTER CONTROLLER -------------
export const INCOMPLETE_REGISTER_FORM: number = 322;
export const INVALID_USER_INPUT_REGISTER: number = 323;
export const USERNAME_EXIST_REGISTER: number = 324;
export const EMAIL_EXIST_REGISTER: number = 325;

// * ------------- ACTIVATE CONTROLLER -------------
export const INCOMPLETE_REGISTER_FORM_ACTIVATE: number = 326;
export const INVALID_USER_INPUT_REGISTER_ACTIVATE: number = 327;
export const USERNAME_EXIST_REGISTER_ACTIVATE: number = 328;
export const EMAIL_EXIST_REGISTER_ACTIVATE: number = 329;
export const EXPIRED_ACCOUNT_ACTIVATION_JWT_TOKEN_OR_INVALID_ACCOUNT_ACTIVATION_JWT_TOKEN: number = 330;
export const NO_ACCOUNT_ACTIVATION_JWT_TOKEN: number = 331;

// * ------------- FORGOT PASSWORD CONTROLLER -------------
export const INCOMPLETE_FORGOT_PASSWORD_FORM: number = 332;
export const INVALID_USER_INPUT_FORGOT_PASSWORD: number = 333;
export const EMAIL_NOT_EXIST_FORGOT_PASSWORD: number = 334;
export const USER_SSO_ACCOUNT_FORGOT_PASSWORD: number = 335;

// * ------------- RESET PASSWORD CONTROLLER -------------
export const NO_JWT_TOKEN_OR_CSRF_TOKEN_RESET_PASSWORD: number = 336;
export const EXPIRED_LINK_OR_INVALID_CSRF_TOKEN_RESET_PASSWORD: number = 337;
export const EXPIRED_LINK_OR_INVALID_JWT_TOKEN_RESET_PASSWORD: number = 338;
export const INCOMPLETE_RESET_PASSWORD_FORM: number = 339;
export const PASSWORD_REPEAT_PASSWORD_NOT_MATCH_RESET_PASSWORD_FORM: number = 340;
export const INVALID_USER_INPUT_RESET_PASSWORD: number = 341;
export const EMAIL_NOT_EXIST_RESET_PASSWORD: number = 342;
export const USER_SSO_ACCOUNT_RESET_PASSWORD: number = 343;
export const INVALID_CSRF_TOKEN_RESET_PASSWORD: number = 344;

// * ------------- ACCOUNT RECOVERY RESET PASSWORD VERIFY TOKEN CONTROLLER -------------
export const NO_JWT_TOKEN_OR_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN: number = 345;
export const EXPIRED_LINK_OR_INVALID_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN: number = 346;
export const EXPIRED_LINK_OR_INVALID_JWT_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN: number = 347;
export const INCOMPLETE_FORGOT_PASSWORD_FORM_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN: number = 348;
export const INVALID_USER_INPUT_FORGOT_PASSWORD_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN: number = 349;
export const EMAIL_NOT_EXIST_OR_USER_NOT_REQUEST_FORGOT_PASSWORD_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN: number = 350;
export const INVALID_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN: number = 351;

// * ------------- SSO SIGN IN GOOGLE IDENTITY SERVICES -------------
export const NO_SSO_JWT_TOKEN_SSO_SIGN_IN_GOOGLE_IDENTITY_SERVICES: number = 352;
export const PAYLOAD_UNDEFINED_SSO_SIGN_IN_GOOGLE_IDENTITY_SERVICES: number = 353;
export const FAILED_VALIDATION_SSO_SIGN_IN_GOOGLE_IDENTITY_SERVICES: number = 354;
export const INCOMPLETE_CREDENTIAL_SSO_SIGN_IN_GOOGLE_IDENTITY_SERVICES: number = 355;
export const INVALID_CREDENTIAL_SSO_SIGN_IN_GOOGLE_IDENTITY_SERVICES: number = 356;
export const USER_NOT_EXIST_SSO_SIGN_IN_GOOGLE_IDENTITY_SERVICES: number = 357;

// * ------------- SSO SIGN UP GOOGLE IDENTITY SERVICES -------------
export const NO_SSO_JWT_TOKEN_SSO_SIGN_UP_GOOGLE_IDENTITY_SERVICES: number = 358;
export const PAYLOAD_UNDEFINED_SSO_SIGN_UP_GOOGLE_IDENTITY_SERVICES: number = 359;
export const FAILED_VALIDATION_SSO_SIGN_UP_GOOGLE_IDENTITY_SERVICES: number = 360;
export const INCOMPLETE_CREDENTIAL_SSO_SIGN_UP_GOOGLE_IDENTITY_SERVICES: number = 361;
export const INVALID_CREDENTIAL_SSO_SIGN_UP_GOOGLE_IDENTITY_SERVICES: number = 362;
export const USER_ALREADY_EXIST_SSO_SIGN_UP_GOOGLE_IDENTITY_SERVICES: number = 363;

// * ------------- SSO SIGN IN FIREBASE FACEBOOK -------------
export const NO_SSO_JWT_TOKEN_SSO_SIGN_IN_FIREBASE_FACEBOOK: number = 364;
export const FAILED_DELETE_ACCOUNT_IN_FIREBASE_DATABASE_SSO_SIGN_IN_FIREBASE_FACEBOOK: number = 365;
export const INCOMPLETE_CREDENTIAL_SSO_SIGN_IN_FIREBASE_FACEBOOK: number = 366;
export const INVALID_CREDENTIAL_SSO_SIGN_IN_FIREBASE_FACEBOOK: number = 367;
export const USER_NOT_EXIST_SSO_SIGN_IN_FIREBASE_FACEBOOK: number = 368;

// * ------------- SSO SIGN UP FIREBASE FACEBOOK -------------
export const NO_SSO_JWT_TOKEN_SSO_SIGN_UP_FIREBASE_FACEBOOK: number = 369;
export const FAILED_DELETE_ACCOUNT_IN_FIREBASE_DATABASE_SSO_SIGN_UP_FIREBASE_FACEBOOK: number = 370;
export const INCOMPLETE_CREDENTIAL_SSO_SIGN_UP_FIREBASE_FACEBOOK: number = 371;
export const INVALID_CREDENTIAL_SSO_SIGN_UP_FIREBASE_FACEBOOK: number = 372;
export const USER_ALREADY_EXIST_SSO_SIGN_UP_FIREBASE_FACEBOOK: number = 373;

// * ------------- SSO SIGN IN FIREBASE GOOGLE -------------
export const NO_SSO_JWT_TOKEN_SSO_SIGN_IN_FIREBASE_GOOGLE: number = 374;
export const FAILED_DELETE_ACCOUNT_IN_FIREBASE_DATABASE_SSO_SIGN_IN_FIREBASE_GOOGLE: number = 375;
export const INCOMPLETE_CREDENTIAL_SSO_SIGN_IN_FIREBASE_GOOGLE: number = 376;
export const EMAIL_NOT_VERIFIED_SSO_SIGN_IN_FIREBASE_GOOGLE: number = 377;
export const INVALID_CREDENTIAL_SSO_SIGN_IN_FIREBASE_GOOGLE: number = 378;
export const USER_NOT_EXIST_SSO_SIGN_IN_FIREBASE_GOOGLE: number = 379;

// * ------------- SSO SIGN UP FIREBASE GOOGLE -------------
export const NO_SSO_JWT_TOKEN_SSO_SIGN_UP_FIREBASE_GOOGLE: number = 380;
export const FAILED_DELETE_ACCOUNT_IN_FIREBASE_DATABASE_SSO_SIGN_UP_FIREBASE_GOOGLE: number = 381;
export const INCOMPLETE_CREDENTIAL_SSO_SIGN_UP_FIREBASE_GOOGLE: number = 382;
export const EMAIL_NOT_VERIFIED_SSO_SIGN_UP_FIREBASE_GOOGLE: number = 383;
export const INVALID_CREDENTIAL_SSO_SIGN_UP_FIREBASE_GOOGLE: number = 384;
export const USER_ALREADY_EXIST_SSO_SIGN_UP_FIREBASE_GOOGLE: number = 385;

// * ------------- DELETE USER CONTROLLER -------------
export const USER_NOT_EXIST_DELETE_USER: number = 386;
export const FAILED_DELETE_ACCOUNT_IN_FIREBASE_DATABASE_DELETE_USER: number = 387;

// * ------------- MODEL MONGOOSE VALIDATION ERROR -------------
export const MONGOOSE_VALIDATION_ERROR: number = 499;

// * ------------- SERVER ERROR -------------
export const SERVER_ERROR: number = 500;

