export const JWT_AUTHENTICATION_TOKEN_EXPIRATION_STRING: string = "60m";            // * HOW LONG THE USER CAN BE AUTHENTICATED WHEN SUCCESS IN LOGIN?

// * ---------------- FOR EMAIL ----------------
export const JWT_REGISTER_ACCOUNT_ACTIVATION_EXPIRES_IN_STRING: string = "5m";      // * HOW LONG THE EMAIL REGISTER ACCOUNT ACTIVATION LINK TO BE EXPIRED
export const JWT_ACCOUNT_RECOVERY_RESET_PASSWORD_EXPIRES_IN_STRING: string = "5m";  // * HOW LONG THE EMAIL ACCOUNT RECOVERY RESET PASSWORD LINK TO BE EXPIRED

// * ---------------- FOR MULTI FACTOR AUTHENTICATION LOGIN CODE ----------------
export const JWT_MFA_LOGIN_TOKEN_EXPIRATION_STRING: string = "5m";                  // * HOW LONG THE MULTI FACTOR AUTHENTICATION TO BE ENDED BEFORE LOGIN AGAIN?