// * CUSTOMIZE COOKIES NAMES
export const COOKIE_AUTHENTICATION_TOKEN_NAME: string = "AUTH_TOKEN";           // * NAME OF THE COOKIE AUTHENTICATION TOKEN (AUTHENTICATED USER COOKIE)
export const COOKIE_CSRF_TOKEN_NAME: string = "XSRF_TOKEN";                     // * NAME OF THE COOKIE CSRF TOKEN (AUTHENTICATED USER CSRF TOKEN OR PUBLIC CSRF TOKEN (WHEN NOT LOGGED IN))
export const COOKIE_MFA_TOKEN_NAME: string = "MFA_TOKEN";                       // * NAME OF THE COOKIE USER MULTI FACTOR AUTHENTICATION TOKEN (AUTHENTICATED USER)

// * CUSTOMIZE COOKIES EXPIRATIONS
export const COOKIE_AUTHENTICATION_TOKEN_EXPIRATION: number = 60 * 1000 * 60;   // * HOW LONG THE USER CAN BE AUTHENTICATED WHEN SUCCESS IN LOGIN?
export const COOKIE_PUBLIC_CSRF_TOKEN_EXPIRATION: number = 60 * 1000 * 60;       // * HOW LONG THE PUBLIC CSRF TO BE EXPIRED
export const COOKIE_MFA_LOGIN_TOKEN_EXPIRATION: number = 60 * 1000 * 5;         // * HOW LONG THE MULTI FACTOR AUTHENTICATION TO BE ENDED BEFORE LOGIN AGAIN?